### ISSUE TITLE
[FEAT]: 

### ISSUE THREAD

**Issue by 91XX** [BartoszCichecki/LenovoLegionToolkit#542] opened 2023-02-08 15:38 UTC
### Version

2.9.0

### OS

Edition	Windows 11 Home Single Language Version	22H2 Installed on	‎1/‎9/‎2023 OS build	22621.1105 Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

No available option to add turn-off displays as a shortcut in smart key action.
![image](https://user-images.githubusercontent.com/98228741/217576763-ca6258fc-76be-4bcc-bc58-669ef7fa3ec1.png)
![image](https://user-images.githubusercontent.com/98228741/217576869-cf82f3f1-0270-4d47-ab7a-2f142f5c94a6.png)

### How would you like the problem to be solved?

Ability to add custom actions to the smart key action.

### What alternatives have you considered?

None

**Comment by BartoszCichecki** [comment] 2023-02-08 15:40
Duplicate of #541

**Closed by BartoszCichecki** 2023-02-08 15:40 UTC
Labels: feature

**Comment by BartoszCichecki** [comment] 2023-02-08 15:42
Maybe try creating the quick action first? :>

**Comment by 91XX** [comment] 2023-02-08 17:35
Thanks...and keep up the great work😊
