### ISSUE TITLE
[FEAT]: Custom Mode for Legion R9000X ARHA7 AMD version

### ISSUE THREAD

**Issue by an4k1n** [BartoszCichecki/LenovoLegionToolkit#475] opened 2023-01-08 17:02 UTC
### Version

2.8.0 BETA 1

### OS

Windows 11 22H2 Build 22621.963

### Device

Legion R9000X ARHA7

### Is your feature request related to a problem?

Can you enable custom mode for legion slim 7 AMD 6800H+ RX6800s
BIOS version : KFCN30WW

### How would you like the problem to be solved?

Can you enable custom mode for legion slim 7 AMD 6800H+ RX6800s
BIOS version : KFCN30WW

### What alternatives have you considered?

Can you enable custom mode for legion slim 7 AMD 6800H+ RX6800s
BIOS version : KFCN30WW

**Comment by BartoszCichecki** [comment] 2023-01-08 17:10
Duplicate of #459. Bios version 32 is minimum

**Closed by BartoszCichecki** 2023-01-08 17:10 UTC
Labels: feature
