### ISSUE TITLE
Unhandled exception when switching performance modes

### ISSUE THREAD

**Issue by kevtang** [BartoszCichecki/LenovoLegionToolkit#1005] opened 2023-10-25 23:20 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Widnows 11  22H2

### Device

Legion 7 Slim 16ACH7 (2022 AMD)

### BIOS version

KFCN33WW

### What's wrong?

close to 100% reproducible - but when I had a game (Overwatch) open and I switch performance modes using fn+q, lenovo toolkit crashes with the following error:

Application: Lenovo Legion Toolkit.exe
CoreCLR Version: 6.0.2123.36311
.NET Version: 6.0.21
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: An item with the same key has already been added. Key: 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at LenovoLegionToolkit.Lib.System.Management.WMI.LenovoIntelligentOPList.ReadAsync()
   at LenovoLegionToolkit.Lib.Controllers.AIController.EnableAsync()
   at LenovoLegionToolkit.Lib.Controllers.AIController.RefreshAsync()
   at LenovoLegionToolkit.Lib.Utils.ThrottleLastDispatcher.DispatchAsync(Func`1 task)
   at LenovoLegionToolkit.Lib.Controllers.AIController.PowerModeListener_Changed(Object sender, PowerModeState e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

  

### How to reproduce the bug?

1. Open a full screen game (in this case it was in an external monitor with freesync pro)
2. switch performance modes a couple of times using fn+q
3. tool kit crashes with the popup of the exception

### What is the behavior that you expected?

no crashes

### Logs

[error_2023_10_25_22_24_53.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13171473/error_2023_10_25_22_24_53.txt)

**Comment by jilievthinkink** [comment] 2023-10-26 02:23
Same error/crash here on 16ARHA7 - L7Slim AMD 2022
Also running same firmware (which I believe is the latest that Windows update will install)

Couldn't copy&paste text so used OCR: 

Application Domain Error
Unexpected exception occurred:
System.ArgumentException: An item with the same key has already
been added. Key:
at bool System.ColIections.GenericDictionary<TKey,
TValue>.Trylnsert(TKey key, TValue value, InsertionBehavior behavior)
at Dictionary<TKey, TEIement>
System.Linq.Enumerable.ToDictionary<TSource, TKey,
source, Func<TSource, TKey>
keySelector, Func<TSource, TEIement> elementSelector,
comparer) x 2
at async Task<Dictionary<string, int> >
LenovoLegionTooIkit.Lib.System Management.WMI+LenovoInteIIigent
OPList.ReadAsync0
at async Task
LenovoLegionToolkit.Lib.Controllers.AlController.EnableAsync0
at async Task
LenovoLegionToolkit.Lib.Controllers.AlController.RefreshAsync0
at async Task
LenovoLegionToolkit.Lib.Utils.ThrottleLastDispatcher.DispatchAsync(Fu
nc<Task> task)
at async void
LenovoLegionTooIkit.Lib.ControIIersAControIIer.GameAutoListener_C
hanged(object sender, bool e)
at void System.Threading.Task5.Task.ThrowAsync(Exception exception,
SynchronizationContext targetContext)+(object state) = > { }
at bool System.Threading.ThreadPoolWorkQueue.Dispatch()
at void
System. Threading. PortableThreadPool + WorkerThread.WorkerThreadSt
art()
at void System.Threading.Thread.StartCallback0
Please report the issue on
https://github.com/BartoszCichecki/LenovoLegionTool kit.

**Comment by BartoszCichecki** [comment] 2023-10-26 15:52
Duplicate of #997

BETA build is as usual available on Discord linked on the project page or you can get the installer from here before new version is released: https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/6646561027.

**Closed** 2023-10-26 15:52 UTC
Labels: bug
