### ISSUE TITLE
[BUG]: Notifications not appearing for power mode change

### ISSUE THREAD

**Issue by rp1231** [BartoszCichecki/LenovoLegionToolkit#351] opened 2022-11-05 08:16 UTC
### Version

2.6.4

### OS

Windows 11 22h2

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN51WW

### What's wrong?

In the vantage software there is an overlay notification shown when you change the power mode.
The overlay doesn't appear for the power mode in lenovolegiontoolkit

### How to reproduce the bug?

Press the Fn+Q hotkey to change the power mode.

### What is the behavior that you expected?

An overlay notification should appear showing which power mode you have selected.

### Logs

Let me know if a log is needed for this.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment] 2022-11-05 08:52
This is not a bug, this feature wasn't implemented yet.

**Comment by BartoszCichecki** [comment] 2022-11-05 08:52
Duplicate of #244.

**Closed** 2022-11-05 08:52 UTC
Labels: bug
