### ISSUE TITLE
[FEAT]: 

### ISSUE THREAD

**Issue by 3397871142** [BartoszCichecki/LenovoLegionToolkit#305] opened 2022-10-18 15:54 UTC
### Version

2.6.3

### OS

win11 22h2

### Device

r9000p2021

### Is your feature request related to a problem?

I hope to add fn to raise the light, and the rear Y headlight switch prompt

### How would you like the problem to be solved?

Instead, it's like a prompt to disable the microphone camera

### What alternatives have you considered?

Replace with something like a hint in the lower right corner

### Additional information

Hopefully this feature is added, it will be better

**Comment by 3397871142** [comment] 2022-10-18 23:45
You can add hints for the fn light keys on your keyboard

> 对不起，我不明白你在说什么。

**Comment by 3397871142** [comment] 2022-10-18 23:46
> 对不起，我不明白你在说什么。
Sorry, my English is not very good

**Comment by 3397871142** [comment] 2022-10-18 23:54
> 对不起，我不明白你在说什么。

Added keyboard backlight prompt

**Comment by BartoszCichecki** [comment] 2022-10-19 07:08
@KarlLee830 can you help here?

**Comment by KarlLee830** [comment] 2022-10-19 08:49
> @KarlLee830 can you help here?

Of course, what he meant was that he wanted to be able to add notifications for switching the keyboard backlight and switching the lights on the back of the laptop, just like notifications for switching the microphone and camera.

**Comment by BartoszCichecki** [comment] 2022-10-19 08:51
Ah, understood. In this case I will close this because it will be covered by #244.

**Comment by BartoszCichecki** [comment] 2022-10-19 08:52
Duplicate of #244.

**Closed by BartoszCichecki** 2022-10-19 08:52 UTC
Labels: feature, needs-clarification

**Comment by KarlLee830** [comment] 2022-10-19 08:54
@3397871142 作者说因为和 #244 是一样的issue，所以他关掉了这个issue。

**Comment by KarlLee830** [comment] 2022-10-19 09:02
如果你不会使用issue和英语，欢迎加入LLT中文反馈交流QQ频道哈
我会帮助收集中文用户的问题并反馈给作者的
https://pd.qq.com/s/jj0737
@3397871142
