### ISSUE TITLE
[FEAT]: we need Gpu overclocking

### ISSUE THREAD

**Issue by lym1932002643** [BartoszCichecki/LenovoLegionToolkit#268] opened 2022-10-11 23:58 UTC
### Version

2.6.2

### OS

Windows 11 22h2 22623.741

### Device

y9000p 2022

### Is your feature request related to a problem?

We hope to open the same GPU overclocking function as that in the legion zone and vantage

### How would you like the problem to be solved?

We hope to open the same GPU overclocking function as that in the legion zone and vantage

### What alternatives have you considered?

no

**Comment by BartoszCichecki** [comment] 2022-10-12 06:55
There is no plans for adding GPU over clocking. Use something like MSI afterburner.

Duplicate of #216

**Closed** 2022-10-12 06:56 UTC
Labels: feature
