### ISSUE TITLE
[BUG]: It's crashed error is 34304

### ISSUE THREAD

**Issue by Steven9178Anotheraccount** [BartoszCichecki/LenovoLegionToolkit#261] opened 2022-10-10 13:01 UTC
### Version

2.62

### OS

Windows 11 22H2 22621.608

### Device

Lenovo IdeaPad 5 Pro ARH7/Lenovo Xiaoxin Pro 16 ARH7

### BIOS version

J4CN33WW

### What's wrong?

![图片](https://user-images.githubusercontent.com/115457858/194863807-c911e166-3241-473f-89a6-57035cfb5505.png)

### How to reproduce the bug?

1. Go to Dashboard
2. Find "Betty Mode"
3. Click "Rapid  Charge"

### What is the behavior that you expected?

Fix it

### Logs

error log
=== Exception ===
System.InvalidOperationException: Unknown battery state: 34304
   at LenovoLegionToolkit.Lib.Features.BatteryFeature.FromInternalAsync(UInt32 state)
   at LenovoLegionToolkit.Lib.Features.AbstractDriverFeature`1.GetStateAsync()
   at LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl`1.OnStateChange(ComboBox comboBox, IFeature`1 feature, Nullable`1 newValue, Nullable`1 oldValue)
   at LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl`1.ComboBox_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.InvalidOperationException: Unknown battery state: 34304
   at Task<BatteryState> LenovoLegionToolkit.Lib.Features.BatteryFeature.FromInternalAsync(uint state)
   at async Task<T> LenovoLegionToolkit.Lib.Features.AbstractDriverFeature<T>.GetStateAsync()
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl<T>.OnStateChange(ComboBox comboBox, IFeature<T> feature, T? newValue, T? oldValue)
   at async void LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl<T>.ComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)

normal log
=== Exception ===
System.InvalidOperationException: Unknown battery state: 34304
   at LenovoLegionToolkit.Lib.Features.BatteryFeature.FromInternalAsync(UInt32 state)
   at LenovoLegionToolkit.Lib.Features.AbstractDriverFeature`1.GetStateAsync()
   at LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl`1.OnStateChange(ComboBox comboBox, IFeature`1 feature, Nullable`1 newValue, Nullable`1 oldValue)
   at LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl`1.ComboBox_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.InvalidOperationException: Unknown battery state: 34304
   at Task<BatteryState> LenovoLegionToolkit.Lib.Features.BatteryFeature.FromInternalAsync(uint state)
   at async Task<T> LenovoLegionToolkit.Lib.Features.AbstractDriverFeature<T>.GetStateAsync()
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl<T>.OnStateChange(ComboBox comboBox, IFeature<T> feature, T? newValue, T? oldValue)
   at async void LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl<T>.ComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by Steven9178Anotheraccount** [comment] 2022-10-10 14:27
Okay

**Comment by BartoszCichecki** [comment] 2022-10-11 06:30
Duplicate of #257

**Closed by BartoszCichecki** 2022-10-11 06:30 UTC
Labels: bug
