### ISSUE TITLE
Unable to open the app suddenly

### ISSUE THREAD

**Issue by cy1der** [BartoszCichecki/LenovoLegionToolkit#1326] opened 2024-06-07 20:49 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.2

### OS

Windows 11 Home 23H2 22631.3672

### Device

Legion Slim 7 Gen 8 (AMD)

### BIOS version

M1CN38WW

### What's wrong?

All of a sudden, when I boot up my computer, LLT prompts me to install .NET Desktop Runtime 8.0.6. After I install that and try to open LLT again, it does nothing after I press `yes` for the administrator privileges.

### How to reproduce the bug?

1. Run the app normally

### What is the behavior that you expected?

The dashboard opens and a tray icon is available

### Logs

Here's the issue…

I ran `"%LOCALAPPDATA%\Programs\LenovoLegionToolkit\Lenovo Legion Toolkit.exe" --trace` and then went to `%LOCALAPPDATA%\LenovoLegionToolkit\log` to get the logs, but there are no logs (no folder named “LenovoLegionToolkit”, see picture). Because of this, I suspect the crash is happening on the .NET level?

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/67352978/721f002a-418d-4f46-9772-fc4a516c7d73)

### Additional information

Installed runtimes:
```
Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Here's a video demonstration (I know the administrator popup doesn't show in the video, but I do press `yes`):
https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/67352978/325b2884-7efa-4a0a-9a7c-5ccaef4a6b7f

**Comment by BartoszCichecki** [comment] 2024-06-07 21:13
Duplicate of #1313 (which is pinned by the way).

**Closed by BartoszCichecki** 2024-06-07 21:13 UTC
Labels: bug
