### ISSUE TITLE
[BUG]: Fail to change the built-in resolution

### ISSUE THREAD

**Issue by wkk66** [BartoszCichecki/LenovoLegionToolkit#611] opened 2023-03-13 16:29 UTC
### Version

2.10.0

### OS

Windows 1122621.1265

### Device

Lenovo R9000p2021

### BIOS version

GKCN59WW

### What's wrong?

It is possible to change the built-in resolution when running the specified program, but it will fail to change the built-in resolution when the program is closed. Versions 2.8.1 and earlier do not have this bug, and versions 2.9 and later 2.10 have this bug.
![微信图片_20230314001954](https://user-images.githubusercontent.com/127773636/224764273-157b06c1-87f4-4cbf-9a33-be1e5dc20c0e.jpg)
![微信图片_20230314002000](https://user-images.githubusercontent.com/127773636/224764289-2279e3c3-020b-42fc-ae94-203aaee8f548.jpg)
![微信图片_20230314001943](https://user-images.githubusercontent.com/127773636/224764293-3d9ec343-6270-45d7-a884-88e9a5f219ce.jpg)

### How to reproduce the bug?

Versions 2.9 and above automatically change the built-in resolution when the program is opened and run successfully, but it will fail to change the built-in resolution when the program is closed and running. Versions 2.8 and earlier do not have this bug

### What is the behavior that you expected?

It is expected that the automatic startup program changes the resolution successfully, and the shutdown program changes the resolution successfully

### Logs

[log.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10959473/log.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment] 2023-03-13 16:56
Can you upload a log from version 2.8.1 too?

**Comment by wkk66** [comment] 2023-03-13 18:49
> 您也可以上传2.8版的日志吗？或者以最后一个工作为准。
> 
> 另外，您可以从仪表板切换到两种分化率吗？
This is the bug-free running log of 2.8.1, currently using 2.8, because this version automatically opens the software and closes the software to change the resolution without bugs, I hope to fix this bug in the new version, version 2.9. 2.10 has this bug. Thank you, please fix it as soon as possible
[log_2023_03_13_18_42_49.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10960769/log_2023_03_13_18_42_49.txt)

**Comment by BartoszCichecki** [comment] 2023-03-13 19:07
Could you please try this build and check if it fixes the issue? Please also attach the log.
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10960879/LenovoLegionToolkitSetup.zip)

I am not completely sure where the problem is, so we will have to try couple of things.

**Comment by wkk66** [comment] 2023-03-13 20:41
> 你能试试这个版本并检查它是否解决了问题吗？请同时附上日志。 [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10960879/LenovoLegionToolkitSetup.zip)
> 
> 我不完全确定问题出在哪里，所以我们将不得不尝试一些事情。



> Could you please try this build and check if it fixes the issue? Please also attach the log. [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10960879/LenovoLegionToolkitSetup.zip)
> 
> I am not completely sure where the problem is, so we will have to try couple of things.

[log_2023_03_13_20_37_18.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10961741/log_2023_03_13_20_37_18.txt)
It’s ok, now the built-in resolution can be adjusted after automatically closing the program, thank you, please update the official version

**Comment by BartoszCichecki** [comment] 2023-03-13 20:42
Great to hear! You can keep using this version for now. An update will be released later this week or early next week.

**Closed by BartoszCichecki** 2023-03-13 20:42 UTC
Labels: bug

**Comment by wkk66** [comment] 2023-03-13 20:48
Okay, thank you. Wait for the good news.
