### ISSUE TITLE
Legion 5 Pro 16ARH7H

### ISSUE THREAD

**Issue by trevlungul** [BartoszCichecki/LenovoLegionToolkit#164] opened 2022-08-09 16:53 UTC
**First and foremost**
Did you read the whole README? 
Yes

**Environment (please complete the following information):**
 - OS: 
 Windows 10 19044.1826
 - Laptop model: 
 Legion 5 Pro 16ARH7H
.NET version: 4.8
No Vantage installed

**List of features that are working as expected**
All mostly

**List of features that seem to not work**
Disconnect GPU? LLT shows that the GPU is disconnected/inactive, but I always have the GPU connected

**List of features that crash the app**
no crash

**Additional context**
The GPU will always show as a connected device. LLT does show a power draw of ~24W. If I eject the device the power draw will fall considerably (~7w)
<img width="189" alt="JIAZUBvP36" src="https://user-images.githubusercontent.com/110926138/183710354-9a82fce8-e7c0-4251-b5ae-22dbea510a8f.png">
Trying to kill apps doesn't change anything. The GPU will always be connected like this regardless of LLT even being installed, so I'm not sure if it's a Windows problem (I've also confirmed the same situation with Win.11) or BIOS 
Perhaps if nothing else I'd like to make a feature request that would "eject the device" under the actions/quick actions menu

**Comment by BartoszCichecki** [comment] 2022-08-16 20:17
Duplicate of #162.

**Comment by BartoszCichecki** [comment] 2022-08-16 20:17
As an FYI: LLT has nothing to do with whether the dGPU is connected or not.

**Closed by BartoszCichecki** 2022-08-16 20:17 UTC
Labels: compatibility
