### ISSUE TITLE
Option to disable the tray icon

### ISSUE THREAD

**Issue by matias1233218** [BartoszCichecki/LenovoLegionToolkit#1024] opened 2023-11-07 17:50 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.0

### OS

Windows 10 22h2

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

One feature that the llt has is that when using it it always has a tray icon in the corner tray of Windows.
From what I see, unlike other programs, in llt there is no option to deactivate the icon, so it stays there

### How would you like the problem to be solved?

adding the feature of disabling the tray icon, so that the tray looks cleaner

### What alternatives have you considered?

It can be hidden, but in cases where you do not have another program running, it will be the only one that shows that arrow with hidden icons

**Comment by BartoszCichecki** [comment] 2023-11-07 17:52
Duplicate of #352

**Closed** 2023-11-07 17:52 UTC
Labels: feature
