### ISSUE TITLE
[FEAT]: Setup OC profiles from BIOS

### ISSUE THREAD

**Issue by Prakyy** [BartoszCichecki/LenovoLegionToolkit#517] opened 2023-01-28 14:46 UTC
### Version

2.8.1

### OS

Windows 11 22H2 Build 22621

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

Setting GPU overclocking in the BIOS relies on the Lenovo Vantage app to set the GPU and VRAM clocks upon boot. If running LLT with vantage disabled (as recommended), these OC profiles are not applied.

### How would you like the problem to be solved?

Read OC profile from BIOS and apply once on boot, just like vantage does.

### What alternatives have you considered?

n/a

**Comment by BartoszCichecki** [comment] 2023-01-28 14:56
Duplicate of #216.

**Closed by BartoszCichecki** 2023-01-28 14:56 UTC
Labels: feature
