### ISSUE TITLE
[FEAT]: 

### ISSUE THREAD

**Issue by Spoof14** [BartoszCichecki/LenovoLegionToolkit#627] opened 2023-03-19 15:04 UTC
### Version

2.11.2

### OS

Windows 11

### Device

5i Pro 16IAH7H

### Is your feature request related to a problem?

Laptop gets pretty hot when the gpu is on, even if it's just powering a monitor.

### How would you like the problem to be solved?

Make an action to change between GPU Working modes when opening / closing games. I understand this will only work when using a display output that's wired through the CPU

### What alternatives have you considered?

Lowering power consumption of cpu and gpu, but GPU is already in low power mode and cpu power limiting is only available in custom mode and it's kinda finnicky

### Additional information

About 20-30 temperature differential in the CPU when idling / light browser usage when switching between GPU modes

**Comment by BartoszCichecki** [comment] 2023-03-19 15:56
Duplicate of #401 #579.

Also,

> Laptop gets pretty hot when the gpu is on, even if it's just powering a monitor.

Display outputs are hard wired to dGPU, so not sure what do you want to achieve.

**Closed by BartoszCichecki** 2023-03-19 15:56 UTC
Labels: feature
