### ISSUE TITLE
[FEAT]: Delay system sleep on lid close to allow Actions to finish running

### ISSUE THREAD

**Issue by Pizoi** [BartoszCichecki/LenovoLegionToolkit#768] opened 2023-06-06 05:30 UTC
### Version

2.13.2

### OS

Windows 11 Home 22H2 build 22621.1778

### Device

Legion 7 16ARHA7

### BIOS version

K9CN42WW

### What's wrong?

In an effort to turn off the annoying pulsing Legion LED on the lid of the laptop when I close it, I tried setting a 'Lid Close' action in LLT to set the keyboard backlight to 0, and then reset it to 3 on 'Lid Open'. I've had it work twice, randomly, but every other time it fails to adjust the brightness.

I can accomplish the same goal by having the keyboard backlight set to 0 with the 'When Display Turns Off/On' actions, but that requires waiting for Windows to actually turn off the screen after locking the OS (first world problem, I know).

### How to reproduce the bug?

Add a Lid Closed action, and in that action add a Keyboard backlight brightness action set to off.
Add a Lid Opened action, and in that action add a Keyboard backlight brightness action set to 3.

Close lid, wait to see if the Legion LED starts pulsing or not.

### What is the behavior that you expected?

I expected the pulsing Legion LED on the top of the laptop lid to stay off once the lid closed, and for the lights to turn back on upon opening the lid.

### Logs

[log_2023_06_06_05_12_29.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11660247/log_2023_06_06_05_12_29.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

It's insane that there's not an option to just outright disable this functionality without entirely turning off all the RGB. Thanks for doing what you do here and at least making it possible.

**Comment by BartoszCichecki** [comment] 2023-06-06 11:53
Thanks for reporting and nice description. I suspect it might be due to Windows going to sleep quite fast when lid is closed and LLT not having enough time to turn off the keyboard - I'll see what can I do about that.

**Comment by BartoszCichecki** [comment] 2023-06-06 20:23
OK so I looked into the issue and I can't find a way to interrupt Windows going into sleep mode when lid is closed. In fact when it's the _user_ that requests the system to sleep, it will go to sleep (which I guess is by design). I can also interrupt sleep that is due to inactivity of the user.

So I will keep this open for now, in case someone else has an idea and change it into a feature request, because the lid close action works properly, assuming that you do not have Sleep set as a lid close action in Windows settings.

**Comment by Pizoi** [comment] 2023-06-06 23:52
Thank you for your efforts!

For anyone interested, I've managed to circumvent the limitations with a bit of fuckery. First I turned off the laptop going to sleep when the lid is closed in the power settings, instead relying on the 5 minute sleep timer to take care of that (or the ~30 seconds it takes to sleep from the lock screen). I have the 'Lid Closed', as well as a 'When Display Turns Off' action set to disable backlight illumination in LLT. To enable the backlight illumination (the Lid Open action wasn't working here even when adding a 1-3 second delay), I used the 'When Display Turns On' action.

I'm thankful to be able to do this at all with the help of this program. These little things matter for us neurotics!

**Comment by DOGGOWoo** [comment] 2023-06-12 22:57
I think I don't fully understand the issue, but couldn't this just be done by disabling LID closing in Window's Power plan, and setting up Lid Close action to do this?
1) Set Keyboard Brightness to 0
2) Delay for 1-3 seconds
3) Add a run command with the following Executable Path and Arguments:
    Executable Path: rundll32.exe
    Arguments: powrprof.dll, SetSuspendState 0,1,0

**Comment by BartoszCichecki** [comment] 2023-06-13 09:07
That could be a valid workaround too 👍

**Closed** 2023-06-22 16:47 UTC
Labels: feature, help wanted
