### ISSUE TITLE
Incomplete display of GPU information

### ISSUE THREAD

**Issue by Nick8848** [BartoszCichecki/LenovoLegionToolkit#1002] opened 2023-10-22 03:03 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2

### Device

Legion R9000K ARHA7

### BIOS version

K9CN42WW

### What's wrong?

Incomplete display of GPU information

### How to reproduce the bug?

Incomplete display of GPU information

### What is the behavior that you expected?

Hope it can be repaired

### Logs

<img width="928" alt="屏幕截图 2023-10-22 094519" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/32447590/16854a0c-7a2c-42bc-a961-42578cd6e73a">

### Additional information

LLT is very easy to use, much better than the official software.

**Comment by Nick8848** [comment] 2023-10-22 03:05
CUP is 6800H GPU is 6700M

**Comment by BartoszCichecki** [comment] 2023-10-22 07:50
Duplicate of #827

**Closed by BartoszCichecki** 2023-10-22 07:50 UTC
Labels: bug
