### ISSUE TITLE
Application domain error 

### ISSUE THREAD

**Issue by juno-kyojin** [BartoszCichecki/LenovoLegionToolkit#1035] opened 2023-11-16 06:56 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16

### OS

win 11 22h2 build 22621.2715

### Device

Legion 7 R9000k AMD Ryzen 7 6800H 6700M

### BIOS version

K9CN42WW

### What's wrong?

<img width="392" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/136924962/e5a3573a-060b-42e6-89e5-6fc2a77214de">

### How to reproduce the bug?

I don't know, when i turn on LLT, bug realease

### What is the behavior that you expected?

LLT worked

### Logs

[16/11/2023 06:54:58.192] [1] [App.xaml.cs#69:Application_Startup] Flags: IsTraceEnabled: True, Minimized: False, SkipCompatibilityCheck: False, DisableTrayTooltip: False, AllowAllPowerModesOnBattery: False, ForceDisableRgbKeyboardSupport: False, ForceDisableSpectrumKeyboardSupport: False, ForceDisableLenovoLighting: False, ExperimentalGPUWorkingMode: False, EnableHybridModeAutomation: False
[16/11/2023 06:54:58.195] [1] [App.xaml.cs#283:EnsureSingleInstance] Checking for other instances...
[16/11/2023 06:54:58.196] [1] [App.xaml.cs#291:EnsureSingleInstance] Another instance running, closing...
[16/11/2023 06:54:58.231] [1] [LocalizationHelper.cs#151:SetLanguageInternal] Applied culture: vi

**Comment by BartoszCichecki** [comment] 2023-11-16 21:11
Duplicate of #1005

Fix was implemented but not released yet. Beta version is available on Discord.

**Closed** 2023-11-16 21:11 UTC
Labels: bug
