### ISSUE TITLE
Add CPU overclocking 

### ISSUE THREAD

**Issue by Angelhellwolf** [BartoszCichecki/LenovoLegionToolkit#1389] opened 2024-08-11 15:53 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.1

### OS

Windows11 23H2

### Device

Legion R9000P ARX8

### Is your feature request related to a problem?

No, it's just that I'm asking for a new feature

### How would you like the problem to be solved?

Add CPU overclocking function, I want to reduce my CPU voltage, which can be used in the Lenovo zone (provided that CPU overclocking is turned on in the BIOS)

### What alternatives have you considered?

Use UXTU or other tools, but it's too cumbersome

**Comment by BartoszCichecki** [comment] 2024-08-11 16:06
Duplicate of #1376

**Closed** 2024-08-11 16:06 UTC
Labels: feature
