### ISSUE TITLE
[Feature Request] Add screen refresh rate autoswitch when on battery/plugged in

### ISSUE THREAD

**Issue by hacker-biba** [BartoszCichecki/LenovoLegionToolkit#100] opened 2022-05-15 07:41 UTC
It would be great to see this feature in your awesome app. So people could extend the battery life of their laptops with one click.

**Comment by BartoszCichecki** [comment] 2022-05-16 18:56
I agree that will be a nice option, however quite large to implement. Closing this one as duplicate of #36.

**Closed by BartoszCichecki** 2022-05-16 18:56 UTC
