### ISSUE TITLE
Legion 5 15ARP8 Fully compatible

### ISSUE THREAD

**Issue by NotSalvador** [BartoszCichecki/LenovoLegionToolkit#1085] opened 2023-12-15 21:33 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.18.0

### OS

Windows 11 23H2 Build 22631.2861

### Device

Legion 5 15ARP8

### BIOS version

NDCN12WW

### Which features of the application did you test?

- Power Mode
- Battery Mode
- Ao-USB
- Instant Boot
- Flip to Start
- GPU Mode
- Resolution
- Refresh Rate
- DPI
- Inputs

### Which features of the application do not work as expected?

None AFAIK.

**Comment by BartoszCichecki** [comment] 2023-12-18 08:59
Duplicate of #1080

**Comment by BartoszCichecki** [comment] 2023-12-18 08:59
Support was added, but new version wasn't released yet.

**Closed by BartoszCichecki** 2023-12-18 08:59 UTC
Labels: compatibility
