### ISSUE TITLE
Add a Integrated graphics display performance visible panel for the APU and core display related adjustable options

### ISSUE THREAD

**Issue by halo0830** [BartoszCichecki/LenovoLegionToolkit#1386] opened 2024-08-09 20:28 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.1

### OS

Windows 11 Professional Edition Insider Preview 22H2 

### Device

Legion 5 Pro 16ACH6H

### Is your feature request related to a problem?

When discrete graphics cards are disabled, I am concerned about the usage of Integrated graphics displays, and if possible, I would rather know their current power consumption and temperaturegpu

### How would you like the problem to be solved?

Add a Integrated graphics display performance visible panel for the APU

### What alternatives have you considered?

RadeonSoftware

**Comment by BartoszCichecki** [comment] 2024-08-09 20:36
Duplicate of #827

**Closed** 2024-08-09 20:36 UTC
Labels: feature
