### ISSUE TITLE
Lenovo LOQ 15IRX9 i5/4050 game crash to desktop and showed this error notice

### ISSUE THREAD

**Issue by DioDavorta** [BartoszCichecki/LenovoLegionToolkit#1141] opened 2024-01-26 00:48 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.19.0

### OS

Windows 11 23H2

### Device

LOQ 15IRX9

### BIOS version

NECN27WW

### What's wrong?

I play RDR2 Lastest Patch, and 30 minutes to 1 hour of gameplay it crashed to desktop, and showed a notice as the image attached. happen multiple times, this bug wont happen if i use Lenovo Vantage instead of LLT.

![Screenshot 2024-01-26 073319](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/157767660/49a3679a-2f10-41c0-a495-82d2575b173d)

### How to reproduce the bug?

1. Start the game normally with balanced mode (AI Engine on)
2. play the game for couple of minutes
3. open windows start menu, or pause the game and go to desktop
4. play the game again
5. soon the game will freeze and crash to desktop
6. the error notice showed

### What is the behavior that you expected?

noting, i've tested to run the same version of windows and RDR2 with LLT, never get this error.

### Logs

[error_2024_01_26_00_32_03.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14059054/error_2024_01_26_00_32_03.txt)

**Comment by BartoszCichecki** [comment] 2024-01-26 08:52
There were no changes to AI Engine in the latest release, so the latest update isn't causing this - the problem is somewhere else.

Also, looking at the crash LLT crashes **after** RDR2 process exited. You can see it in the log here:
```
   at LenovoLegionToolkit.Lib.Controllers.AIController.DisableAsync()
   at LenovoLegionToolkit.Lib.Controllers.AIController.RefreshAsync()
   at LenovoLegionToolkit.Lib.Utils.ThrottleLastDispatcher.DispatchAsync(Func`1 task)
   at LenovoLegionToolkit.Lib.Controllers.AIController.GameAutoListener_Changed(Object sender, Boolean e)
```
It basically means that AIController is stopping, since game listener detected that game quit.

On the other hand the error indicates that calls to WMI failed. That might as well happen in Vantage - you just don't see it since they don't show errors like this.

My suggestion is that you reinstall Gaming Feature driver, try rebuilding/resetting WMI (guides can be found online) and look into other changes/updates you made on the system.

I will close this issue, since it doesn't look like issue with LLT itself, but feel free to ask any questions here.

**Closed by BartoszCichecki** 2024-01-26 08:52 UTC
Labels: bug

**Comment by DioDavorta** [comment] 2024-01-26 23:54
Hi Bartosz. Thanks for the reply.

I followed the first step to verify the WMI from this guide.
https://www.thewindowsclub.com/how-to-repair-or-rebuild-the-wmi-repository-on-windows-10

Run the cmd, and it showed that the WMI Repository is consistent on my laptop.

so, is it safe to say that it was not caused by WMI problem, but the Gaming Feature driver?

if that's so, i need to know how to reinstall the reinstall Gaming Feature driver, since i can't find any guide or which reinstall Gaming Feature driver that you meant.

Thanks, Best Regard.
