### ISSUE TITLE
Custom Battery Limits!

### ISSUE THREAD

**Issue by Dgamefinisher** [BartoszCichecki/LenovoLegionToolkit#962] opened 2023-09-12 01:40 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 development build 26913.2177

### Device

Legion Slim 7 15ACH6

### Is your feature request related to a problem?

For most legion devices such as my S7 15ACH I cannot set a charge level that I'd like my device to stop charging at excluding conservation mode limiting me to 60%. Unlike a higher level thinkpad charge level isn't technically able to be set. However the idea just hit me in the sense that this app can set your PC's mode to conservation and rapid charge/normal whenever it wants. Can we get a feature that allows a user set charge percentage btwn 60-95% and when this percentage is reached LLT automatically switches to conservation thus keeping the device charged (maybe even turn off conservation at custom percentage). If possible also add like a checkbox for use rapid charge while charging to expedite charging times. User defined charge max would be amazing and would make my PC so much for useful. Thanks team!

### How would you like the problem to be solved?

One of three ways. LLT knows your battery percentage and effectively all that would have to be done is the addition of a small panel in the battery/home screen to allow 
user set charge limit(60<=x<100) at which conservation mode is turned on
user set start charging (>=60%) at which conservation is turned off
rapid charge whilst charging (checkbox would use it instead of normal)
and anything else that makes sense as a charging mode (nothing else comes to mind).

Either implement this as a panel using C# like the rest of the UI using the battery percentage that LLT already knows to decide conservation or charging (rapid or normal) or create a small CLI to allow us to create scheduled tasks and switch charging modes like something of the format LLT chargemode conservation/rapid/normal and LLT battery charge for either percentage or net watts in/out

In the actions tab under automatic actions add a when battery percentage below _ and a when battery percentage above _ because the framework to change battery modes already exists and the limitation is this.

### What alternatives have you considered?

I've tried a few different apps that claim to be able to do the same thing but they all require disabling core isolation in MS defender and they don't work anyway.

**Comment by BartoszCichecki** [comment] 2023-09-12 05:01
Duplicate of #564

**Closed** 2023-09-12 05:01 UTC
Labels: feature
