### ISSUE TITLE
[FEAT]: Add basic system monitoring function

### ISSUE THREAD

**Issue by blufish1234** [BartoszCichecki/LenovoLegionToolkit#679] opened 2023-04-19 10:57 UTC
### Version

2.12.0

### OS

Windows 10 Home edition 21H2 19044.2846

### Device

Lenovo Legion 7i Pro 2021

### Is your feature request related to a problem?

It is not related to a problem

### How would you like the problem to be solved?

Add basic device performance monitoring, like CPU and GPU utilization, clock speed, temperature etc. 

### What alternatives have you considered?

None

**Comment by BartoszCichecki** [comment] 2023-04-19 10:59
Duplicate of #179

**Closed** 2023-04-19 10:59 UTC
Labels: feature
