### ISSUE TITLE
[FEAT]: Ability to have a different custom profile on battery mode than on AC, or customize built-in profiles

### ISSUE THREAD

**Issue by b00rek** [BartoszCichecki/LenovoLegionToolkit#645] opened 2023-03-28 12:34 UTC
### Version

2.11.2

### OS

Windows 11 Pro 22H2 22621.1265

### Device

Legion 5 Pro 16IAH7H

### Is your feature request related to a problem?

I'm very happily using custom power mode, with customized power limits and, most importantly to me, a custom fan curve. Whenever I unplug the AC adapter and laptop switches to battery power, it automatically switches to one of the built-in profiles. As a consequence, it switches to different power limits and different fan curve I have no control over.

### How would you like the problem to be solved?

I see a couple of ways to solve this problem:

- Add the ability to customize profiles Quiet, Balanced and Performance.
- Add the ability to specify on Actions pane which Custom profile is loaded on battery power and which one is loaded on AC power. Additionally, a short popup with loaded profile name or customizable power button LED color would be nice to reassure you that the correct profile has been loaded in this case.

### What alternatives have you considered?

N/A.

**Comment by BartoszCichecki** [comment] 2023-03-28 12:38
Custom Mode is not available on battery, due to how it was implemented by Lenovo. The Quiet, Balanced and Performance profile can't be modified.

If you want to force Custom Mode regardless of possible unexpected behavior check out: https://github.com/BartoszCichecki/LenovoLegionToolkit#why-i-cant-switch-to-performance-or-custom-power-mode-on-battery

If you do it, you can save two profiles and use actions to toggle between them.

Popups when running actions are currently out of scope, due to Actions architecture.
LED color can't be customize beyond the 4 colors that are already there.

**Closed by BartoszCichecki** 2023-03-28 12:38 UTC
Labels: feature
