### ISSUE TITLE
Can the pop-up prompt feature add an always-on top option?

### ISSUE THREAD

**Issue by RinSky123** [BartoszCichecki/LenovoLegionToolkit#1170] opened 2024-02-16 18:07 UTC
### Rules

- [X] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

v2.20.2

### OS

Windows10 22h2

### Device

Legion r70002021

### Is your feature request related to a problem?

The current problem is that as long as the program is full screen, you can't see the prompt pop-up window.

### How would you like the problem to be solved?

I just wish I could add an always-on top option, so that pop-ups are available at any time.

### What alternatives have you considered?

no.

**Comment by BartoszCichecki** [comment] 2024-02-16 19:00
Duplicate of #980

**Closed** 2024-02-16 19:01 UTC
Labels: feature
