### ISSUE TITLE
Window glitches after refresh rate change

### ISSUE THREAD

**Issue by mergen3107** [BartoszCichecki/LenovoLegionToolkit#78] opened 2022-02-22 09:31 UTC
I added 60 Hz option to change the screen refresh rate.

Many times, inconsistently, the Lenovo Legion Toolkit window gets some glitches.
Here is one example: 
![LLT_window](https://user-images.githubusercontent.com/6279855/155103334-8d03fd4d-6bf9-496e-9519-b7e02536eabf.png)

Other examples I have seen are when the black area covers part of the window, so I have to restart the LLT.

**Comment by BartoszCichecki** [comment] 2022-03-10 17:13
Duplicate of #45

**Closed by BartoszCichecki** 2022-03-10 17:13 UTC
Labels: duplicate
