### ISSUE TITLE
Legion Toolkit not launching after BIOS update

### ISSUE THREAD

**Issue by dwov** [BartoszCichecki/LenovoLegionToolkit#1286] opened 2024-05-14 20:46 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.2

### OS

Windows 11 23H2 Build 22631

### Device

Legion 7i gen 7

### BIOS version

K1CN46WW

### What's wrong?

After updating my BIOS, the toolkit cannot be launched at all. New BIOS version is the one supplied,

### How to reproduce the bug?

1. Update to latest version
2. Boot
3. Error

### What is the behavior that you expected?

That it would work

### Logs

[error_2024_05_14_20_37_02.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15313643/error_2024_05_14_20_37_02.txt)

**Comment by dwov** [comment] 2024-05-14 20:47
I have also tried reinstalling, both .NET and toolkit

**Comment by BartoszCichecki** [comment] 2024-05-14 21:14
This has nothing to do with BIOS update. WMI on your system is broken. 

Duplicate of #1281

**Closed by BartoszCichecki** 2024-05-14 21:14 UTC
Labels: bug

**Comment by dwov** [comment] 2024-05-15 16:34
I wanted to add to this that it had everything to do with the bios update. For now the latest bios for legion 7i gen 7 doesn't work.

**Comment by BartoszCichecki** [comment] 2024-05-15 18:43
Just updated and got the same crash. Hotfix is released now. This is a first, so apologies for scepticism.

**Comment by dwov** [comment] 2024-05-15 19:55
Thank you sir!
I dont know what I would do without the toolkit.

You are a legend!
