### ISSUE TITLE
Legion 5 Pro Error Crash Screen after a repair session

### ISSUE THREAD

**Issue by Pochiiko** [BartoszCichecki/LenovoLegionToolkit#816] opened 2023-06-25 07:47 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.2

### OS

Windows 11 Pro 22H2

### Device

Legion 5 Pro 

### BIOS version

161AH7H

### What's wrong?

Hovering over the icon crashes the Desktop app, thus sending multiple error reports every time i try to check the stats.

### How to reproduce the bug?

1. disabling the built in battery via the BIOS to add an SSD storage
2. Close the bottom case and plug in AC power
3. boot up windows
4. open hidden icons and hover over the lenovo vantage toolkit icon
5. error pops up (see below)
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/120288342/a253c230-2482-45b5-9b44-ce8899122f7a)

### What is the behavior that you expected?

I expected it to just show the usual stats needed when just hovering over the icon.

### Logs

[error_2023_06_25_07_31_51.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11859086/error_2023_06_25_07_31_51.txt)
[error_2023_06_25_07_32_15.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11859087/error_2023_06_25_07_32_15.txt)

### Additional information

The issue fixes itself after I just re-launch the app.

**Comment by BartoszCichecki** [comment] 2023-06-25 08:25
Duplicate of #673

**Closed by BartoszCichecki** 2023-06-25 08:26 UTC
Labels: bug
