### ISSUE TITLE
Add option to change the order of actions

### ISSUE THREAD

**Issue by 4NXIE7Y** [BartoszCichecki/LenovoLegionToolkit#1465] opened 2024-10-21 10:54 UTC
### Version

2.24.1

### OS

Windows 11 Pro 23H2 Build 22631.4317

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

If I ever wanted to change around the order of actions set in LLT, I would need to delete all the actions happening after it and re-set them.
![image](https://github.com/user-attachments/assets/4d890383-f00f-4faf-b03e-06bdd96f299b)

### How would you like the problem to be solved?

I suggest adding something like this. This is a recording of the Google Keep app.
https://github.com/user-attachments/assets/0415a36d-6232-4c14-995d-095f1fa0372a

### What alternatives have you considered?

None

**Comment by BartoszCichecki** [comment] 2024-10-21 11:18
Right click and select Move Up/Down. Otherwise duplicate of #1358.

**Closed by BartoszCichecki** 2024-10-21 11:18 UTC
Labels: feature
