### ISSUE TITLE
PUA:Win32/Packunwan detection in setup

### ISSUE THREAD

**Issue by h13Bishop** [BartoszCichecki/LenovoLegionToolkit#1394] opened 2024-08-15 20:00 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 11 23H2 22631

### Device

Legion 7 16IAX7

### BIOS version

K1CN45WW

### What's wrong?

Hello.

Starting from 2.23.1 update Windows Defender started to detect PUA:Win32/Packunwan in
> C:\Users\usr\AppData\Local\Temp\LenovoLegionToolkit\LenovoLegionToolkitSetup_be6362dd-88c9-4a5f-aac6-1d920a270ce9.exe
as well as in LenovoLegionToolkitSetup.exe downloaded from here.
Virustotal detects only on Windows.

Is it expected and nothing to worry about?

### How to reproduce the bug?

Press Update button in the program interface.

### What is the behavior that you expected?

The program should update without triggering antivirus.

### Logs

Not a program specific bug.

**Comment by BartoszCichecki** [comment] 2024-08-15 21:29
Duplicate of #1391

**Closed by BartoszCichecki** 2024-08-15 21:29 UTC
Labels: bug

**Comment by h13Bishop** [comment] 2024-08-15 22:07
@BartoszCichecki I'm sorry, I was inattentive while searching
