### ISSUE TITLE
[FEAT]: Fan control on Legion 7 16ARHA7 (AMD model)

### ISSUE THREAD

**Issue by Rinzler081** [BartoszCichecki/LenovoLegionToolkit#454] opened 2022-12-22 01:39 UTC
### Version

2.7.1

### OS

Windows 11 22H2

### Device

Legion 7 82UH / 16ARHA7

### Is your feature request related to a problem?

No fan control on 2022 legion 7 amd

### How would you like the problem to be solved?

add fan control

### What alternatives have you considered?

none yet

**Comment by BartoszCichecki** [comment] 2022-12-22 07:06
Duplicate of #419.

**Closed** 2022-12-22 07:06 UTC
Labels: feature

**Comment by BartoszCichecki** [comment] 2022-12-22 12:27
If you are willing to test, I linked another issue that also has the build posted so you can test.
