### ISSUE TITLE
Notification doesn't show when playing video on full screen

### ISSUE THREAD

**Issue by Arthamna** [BartoszCichecki/LenovoLegionToolkit#1321] opened 2024-06-04 05:36 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.1

### OS

Windows 11 22H2

### Device

Legion Slim 5 16IRH8

### BIOS version

M2CN32WW

### What's wrong?

As i mention in title, LLT notification (un/mute mic, switching mode, disable touchpad, etc), doesn't show when playing any video on full screen, whether on Chrome, Youtube, Brave, or VLC. But, the LLT notification does show when the video is minimize.

### How to reproduce the bug?

1. Open any video
2. Play it on fullscreen
3. Press some button to activate notification
4. Action button (mute mic, etc) worked, but the notification doesnt show.

### What is the behavior that you expected?

The notification is showed, like what it should be when video played

### Logs

[log_2024_06_04_05_33_31.txt](https://github.com/user-attachments/files/15543020/log_2024_06_04_05_33_31.txt)

**Comment by BartoszCichecki** [comment] 2024-06-04 05:57
Duplicate of #980

**Closed by BartoszCichecki** 2024-06-04 05:57 UTC
Labels: bug
