### ISSUE TITLE
[BUG]: Conservation mode turns off upon logging back in

### ISSUE THREAD

**Issue by fredderf121** [BartoszCichecki/LenovoLegionToolkit#492] opened 2023-01-14 23:19 UTC
### Version

2.7.1

### OS

Windows 10 Home 10.0.19044 Build 19044

### Device

Legion 5 15ARH05H

### BIOS version

FSCN26WW

### What's wrong?

When I enable conservation mode through Lenovo Legion Toolkit, it behaves as expected whilst logged in. However, when I log off, shut down, or restart, and then log back in, conservation mode seemingly turns off. 
Additionally, while the computer is logged out / powered off, the conservation mode continues to work, holding battery at 60%. It is only when I log back in does conservation mode turn off and the battery begins to charge. 

### How to reproduce the bug?

1. Have Lenovo Vantage uninstalled
2. Turn on Conservation mode via LLT
3. Have LLT minimize-on-close and Autorun: Enabled
4. Lock the screen (Win-L)
5. Log back in
6. Conservation mode is now off, battery charges past 60%. 

### What is the behavior that you expected?

Conservation mode should always remain on until manually disabled. 

### Logs

All I did was run LLT with logs, logged off, logged back in, and conservation mode was turned off (as in, the battery started charging past 60%). 

[log_2023_01_14_23_15_49.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10419083/log_2023_01_14_23_15_49.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment] 2023-01-14 23:30
Duplicate of #271. 

Also, an upcoming version will have a workaround in place for this, but it's a bug in Lenovos firmware and can't be fixed properly.

**Closed by BartoszCichecki** 2023-01-14 23:30 UTC
Labels: bug

**Comment by BartoszCichecki** [comment] 2023-01-14 23:41
As a side note, latest beta of upcoming version is posted in the Discord server and has the workaround already in place.
