### ISSUE TITLE
Ability to drag steps inside the action

### ISSUE THREAD

**Issue by CodeClimberNT** [BartoszCichecki/LenovoLegionToolkit#1529] opened 2024-12-26 21:01 UTC
### Version

2.24.2

### OS

Windows 11 24h2 Build 26100.2605

### Device

LOQ 15AHP9

### Is your feature request related to a problem?

Rearrange the order of the steps requires a lot of time. Also, if the #1528 issue is found worthy to be implemented, it will increase the amount of step to move together.

The current solution is particularly inconvenient for steps that have different height and its easier to move the wrong one.

### How would you like the problem to be solved?

Mainly adding an object that let the step be dragged up and down, the current single-movement is very useful too, so this would be **only** an addition.

### What alternatives have you considered?

Manually moving the steps on step at the time.

### Additional information

I know I opened three issues very quickly but, while all in the action tab, they require different code structure to be revised.

I hope to see this project continue its development. It's a great utility!

**Comment by BartoszCichecki** [comment] 2024-12-26 21:10
Duplicate of #1358

**Closed** 2024-12-26 21:10 UTC
Labels: feature
