### ISSUE TITLE
[BUG]: Unable to launch application from SYSTEM account

### ISSUE THREAD

**Issue by teconmoon** [BartoszCichecki/LenovoLegionToolkit#574] opened 2023-02-18 19:09 UTC
### Version

2.9.1

### OS

Windows 11 22H2 build 22621.1265

### Device

Legion Y540-15IRH

### BIOS version

BHCN45WW

### What's wrong?

I use my laptop primarily with an unelevated user account and then elevate when necessary. Since the Lenovo Legion Toolkit requires administrator permission to run, I've been attempting to run the application as a service (For example, using NSSM) so that I can configure actions to run in the background regardless of who's logged into the laptop.

I tried launching the application using the SYSTEM account via PsExec so that I could configure it, and instead of the program launching, I received the pictured error:

![image](https://user-images.githubusercontent.com/46909426/219883584-8e4f4517-b74b-4033-bedf-91f916f0b146.png)

### How to reproduce the bug?

Download PSTools and open CMD as an admin. Launch Lenovo Legion Toolkit as SYSTEM using the following command:

**PsExec.exe -accepteula -s -i "Lenovo Legion Toolkit.exe"**

### What is the behavior that you expected?

For the application to open

### Logs

Not applicable as the application doesn't successfully open like this

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

My laptop was a fresh Windows install with no pre-installed Lenovo software.

**Comment by BartoszCichecki** [comment] 2023-02-18 22:52
"Other remarks

LLT currently does not support installation for multiple users, so if you need to have multiple users on you laptop you might encounter issues. Same goes for accounts without Administrator rights - LLT needs an account with Administrator rights. If you install LLT on an account without such rights, LLT will not work properly."

Duplicate of #246

**Closed** 2023-02-18 22:52 UTC
Labels: bug

**Comment by mind12** [comment] 2023-02-19 07:49
@teconmoon Just a quick idea I was working on but not finished yet.
If you enable auto start for LLT there is a scheduled task you can edit. It runs on user logon, so if you put a script that checks if LLT is already running and you kill it and start it again for the current user it should work with multiple accounts.
