### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by eliaspoveda** [BartoszCichecki/LenovoLegionToolkit#425] opened 2022-11-30 00:07 UTC
### Version

2.7.0

### OS

Windows 11 22H2 22621.819

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN55WW

### What's wrong?

When I reboot or shut down the laptop, the battery mode is reset from Conservation to Normal.

### How to reproduce the bug?

1. Set Battery Mode to Conservation.
2. Reset or shut down the computer
3. Battery Mode is automatically set to Normal

### What is the behavior that you expected?

I expected battery mode would remain in conservation mode.

### Logs

I tried following instructions but I can't find the log, sorry.

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment] 2022-11-30 00:47
Duplicate of #120 and #394.

**Closed** 2022-11-30 00:47 UTC
Labels: bug
