### ISSUE TITLE
[BUG]: The Fn Hotkeys OSD of LLT don't work

### ISSUE THREAD

**Issue by Ptilopsis01** [BartoszCichecki/LenovoLegionToolkit#265] opened 2022-10-11 08:05 UTC
### Version

2.6.2CH

### OS

Win11 22H2 22621.608 

### Device

Legion Y9000X IAH7(S7 16IAH7)

### BIOS version

JYCN41WW

### What's wrong?

After disabling the Fn Hotkeys of lenovo, LLT should take over the feature, but even after a rebooting there's no OSD.

### How to reproduce the bug?

1. Disable Fn Hotkey service through LLT
2. Reboot
3. No OSD

### What is the behavior that you expected?

LLT takes over the OSD correctly,

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment] 2022-10-11 08:06
Which OSD? All? Some? Please add more details.

**Comment by DrippyPunk** [comment] 2022-10-11 14:17
> Which OSD? All? Some? Please add more details.

They work for me but they are not visible in fullscreen apps which is kinda annoying, maybe he means that.

**Comment by Ptilopsis01** [comment] 2022-10-11 18:56
> Which OSD? All? Some? Please add more details.
Sorry I didn't describe it clearly.
I mean that LLT should take over the OSD of Lenovo Hotkeys when I turned it off in LLT, but LLT just turned it off and didn't take over this feature, which means I can't see any window or sth like that when I use Fn+Q, for example.

**Comment by BartoszCichecki** [comment] 2022-10-11 20:18
Not all OSD are implemented currently. The ones that work are:
- Microphone (Fn+F4)
- Camera on/off (physical switch on the side)
- Refresh rate (Fn+R)
- Touchpad on/off (Fn+F10)

Fn+Q as an example doesn't currently have any OSD because you can see the change by the color of the power button.

Please test the ones mentioned above. If you are one of the people who would like more OSD, there is already an issue reported here: #244.

**Comment by Ptilopsis01** [comment] 2022-10-12 05:31
> Not all OSD are implemented currently. The ones that work are:
> 
> * Microphone (Fn+F4)
> * Camera on/off (physical switch on the side)
> * Refresh rate (Fn+R)
> * Touchpad on/off (Fn+F10)
> 
> Fn+Q as an example doesn't currently have any OSD because you can see the change by the color of the power button, and that applies to others too. Most people didn't want OSD for changes they can see "on the laptop".
> 
> Please test the ones mentioned above. If you are one of the people who would like more OSD, there is already an issue reported here: #244.

Thx a lot! That's actually what I mean.

**Comment by BartoszCichecki** [comment] 2022-10-12 06:56
Closing as duplicate of #244.

**Closed** 2022-10-12 06:57 UTC
Labels: bug, needs-clarification
