### ISSUE TITLE
New function require

### ISSUE THREAD

**Issue by klfsqwe** [BartoszCichecki/LenovoLegionToolkit#1196] opened 2024-03-01 12:10 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 23H2

### Device

Y9000P RTX4080+i913900HX

### Is your feature request related to a problem?

I can't check the graphics card and CPU power consumption in the software

### How would you like the problem to be solved?

I hope that the display of graphics card and CPU power consumption can be added to the homepage. It would be better if it can be displayed in a floating window. If possible, I hope you can check how many watts the total power consumption of the computer is.

### What alternatives have you considered?

Nothing

**Comment by BartoszCichecki** [comment] 2024-03-01 12:12
Duplicate of #1100

**Closed by BartoszCichecki** 2024-03-01 12:12 UTC
Labels: feature
