### ISSUE TITLE
Fan speed does not match the default value

### ISSUE THREAD

**Issue by awesomenow42** [BartoszCichecki/LenovoLegionToolkit#1324] opened 2024-06-05 00:59 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.2

### OS

Windows 11 23H2 (22631.3672)

### Device

Legion 5 16IRX9

### BIOS version

NMCN22WW

### What's wrong?

Fans in Custom mode by default operate at a minimum speed of 2400 RPM, which does not correspond to the curve and temperature values and creates noise.

Custom - CPU 59 GPU 47 = 2400 RPM
Quiet, Balance or Performance - CPU 60 GPU 48 = 1400 RPM 1700 RPM

### How to reproduce the bug?

Power Mode - Custom - Settings - Default

### What is the behavior that you expected?

According to Fan Curve

### Logs

[log_2024_06_05_00_51_18.txt](https://github.com/user-attachments/files/15571793/log_2024_06_05_00_51_18.txt)

### Additional information

![lltbalance](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/171505401/3396a5dd-26a6-427b-a104-a13b51e7c0f7)
![lltcustom](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/171505401/17932db1-7198-4510-b7f3-ebb960aa8228)
![lltfancurve](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/171505401/e7951e4a-0f66-4ee7-8611-5e1084049ef9)

**Comment by BartoszCichecki** [comment] 2024-06-05 07:04
Duplicate of #1127.

Please check already reported issues next time before creating a new one.

**Closed by BartoszCichecki** 2024-06-05 07:04 UTC
Labels: bug
