### ISSUE TITLE
Feature Request: the ability to control the keyboard lighting more gradually and dimmer while using the keyboard shortcut.

### ISSUE THREAD

**Issue by FatPerson115** [BartoszCichecki/LenovoLegionToolkit#1022] opened 2023-11-07 15:27 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.17.0 BETA 6

### OS

Windows 11 22H2

### Device

Legion Slim 7 16APH8

### Is your feature request related to a problem?

no

### How would you like the problem to be solved?

have the keyboard shortcut fn + down/up arrow control the keyboard brightness with more options instead of just 3, i like having my backlight the lowest option but the fn + down shortcut doesnt go that far down before turning off.

### What alternatives have you considered?

none

**Comment by BartoszCichecki** [comment] 2023-11-07 15:32
Duplicate of #460.

**Closed by BartoszCichecki** 2023-11-07 15:32 UTC
Labels: feature
