### ISSUE TITLE
[FEAT]: want have fans speed display

### ISSUE THREAD

**Issue by HMwancheng** [BartoszCichecki/LenovoLegionToolkit#348] opened 2022-11-04 04:16 UTC
### Version

2.6.4

### OS

win11

### Device

y9000p

### Is your feature request related to a problem?

no

### How would you like the problem to be solved?

can display the fans speed

### What alternatives have you considered?

no

**Comment by BartoszCichecki** [comment] 2022-11-04 07:23
I also want a lot of things. 🙃

Duplicate of #179.

**Closed** 2022-11-04 07:23 UTC
Labels: feature
