### ISSUE TITLE
Set Volume Value

### ISSUE THREAD

**Issue by Halfeez92** [BartoszCichecki/LenovoLegionToolkit#951] opened 2023-09-06 01:10 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2 build 22621

### Device

Legion 7 16ACHg6

### Is your feature request related to a problem?

Everytime I rebooted my laptop, the volume is always reset back to 100%.

### How would you like the problem to be solved?

Can I have the feature to set the volume at certain value?

### What alternatives have you considered?

No alternatives tried. I always had to manually turn down my volume by pressing the Fn key.

**Comment by BartoszCichecki** [comment] 2023-09-06 07:30
Duplicate of #752

**Closed by BartoszCichecki** 2023-09-06 07:30 UTC
Labels: feature
