### ISSUE TITLE
[FEAT]: Option for GPU Overclock

### ISSUE THREAD

**Issue by etson32** [BartoszCichecki/LenovoLegionToolkit#672] opened 2023-04-14 23:41 UTC
### Version

2.12.0

### OS

Windows 11 22H2 22621.1413

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

When I disabled Lenovo Vantage with Lenovo ToolKit options I lost the overclock option, my overclock preset was disabled.

### How would you like the problem to be solved?

Creating an overclock option on Lenovo Tool Kit

### What alternatives have you considered?

Using a the same slider in lenovo vantage

### Additional information

I also take this opportunity to know if a preset could be created with less tdp in the gpu, I would like to be able to have a preset up to 95w (the maximum tdp is 150w), this would improve temperatures and would have low fan noise.

The last update is very good, thank you.

**Comment by BartoszCichecki** [comment] 2023-04-15 09:13
For overclocking use something like Afterburner - it's much better than what was in Vantage. 

Duplicate of #216

**Closed by BartoszCichecki** 2023-04-15 09:13 UTC
Labels: feature
