### ISSUE TITLE
[BUG]: GPU working option not working

### ISSUE THREAD

**Issue by ahweisync** [BartoszCichecki/LenovoLegionToolkit#279] opened 2022-10-15 15:45 UTC
### Version

2.6.2

### OS

Windows 11 Pro

### Device

Legion 5 Pro 16IAH7H

### BIOS version

J2CN43WW

### What's wrong?

GPU working option not working

### How to reproduce the bug?

Set to any GPU working
Check device manager not show up dGPU
Only iGPU

### What is the behavior that you expected?

Set to any GPU working

### Logs

no

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment] 2022-10-15 16:23
Duplicate of #245

**Closed by BartoszCichecki** 2022-10-15 16:23 UTC
Labels: bug
