### ISSUE TITLE
[BUG]: [Ideapad Gaming 3] Touchpad lock notification incorrect after Fn+F10 press

### ISSUE THREAD

**Issue by decipher3114** [BartoszCichecki/LenovoLegionToolkit#429] opened 2022-11-30 16:10 UTC
### Version

2.7.0

### OS

Windows 11 22H2

### Device

Ideapad Gaming 3

### BIOS version

EGCN39WW

### What's wrong?

When I turn off touchpad, it shows touchpad on toast.

### How to reproduce the bug?

Turn off touchpad by key.

### What is the behavior that you expected?

It should show "Touchpad off"

### Logs

No logs.

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment] 2022-11-30 17:40
Can you attach logs?

**Comment by BartoszCichecki** [comment] 2022-12-01 16:19
You says you have Hotkeys installed. Does it work when Hotkeys are enabled? The log is very strange.

**Comment by BartoszCichecki** [comment] 2022-12-01 17:28
But from the video it seems that when you press F10, the notification pops up, but the toggle doesn't move? Also, it is strange that when you toggle touchpad lock on the dashboard the notifications pops up, because it shouldn't.

**Comment by BartoszCichecki** [comment] 2022-12-01 17:39
I am trying to understand what is wrong here before I can fix anything.

**Comment by BartoszCichecki** [comment] 2022-12-01 17:59
We need to do some more troubleshooting. Install this build and toggle the touchpad lock twice on the dashboard and upload a log from it.

[LenovoLegionToolkitSetup_touchpadlock.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10135000/LenovoLegionToolkitSetup_touchpadlock.zip)

**Comment by decipher3114** [comment] 2022-12-02 06:48
As you said, I have no problem with the touchpad status, when the key is pressed, the touchpad does turn off and when pressed again, it turns on again. So, no problem at all. The bug is only the status toast shown on the screen.

**Comment by decipher3114** [comment] 2022-12-02 06:55
Also, I tested with Lenovo hotkeys as well and the working and toast status is both fine.
While with toolkit, working is fine, but toast status is wrong.
https://drive.google.com/file/d/1gUMnzsGHhdZinhM3syRj6dzyvtc6jjk1/view?usp=drivesdk

**Comment by BartoszCichecki** [comment] 2022-12-02 12:23
OK I think I have the full picture now, but I don't have good news.

It seems that on your machine the WMI method for getting touchpad lock state is not returning correct state after Fn+F10 press, however this method works on all Legions correctly. I think that this is another one of these small inconsistencies between different Lenovo laptop line ups.

I will keep this issue open, but since I don't have access to any device that behaves like yours I am not really sure what is the correct method of of checking the state on this model. If someone is willing do some trouble shooting and figure out how to check it I am open to PRs.

**Comment by decipher3114** [comment] 2022-12-02 12:30
Okay, It is fine, I actually never lock the touchpad so, it is fine. Atleast everything else is fine.
👍👍

**Comment by decipher3114** [comment] 2022-12-02 13:08
Also, Can you tell me if there any way I can help you, like showing you system logs or something.
Cause I just checking live logs and there is no change while I change keyboard backlight or even touchpad. Nothing in the logs about this.

**Comment by ElSebasXD-weon** [comment] 2022-12-23 16:21
Hello, I'm having the exact same issue on the same laptop, is there any way I can help on getting this fixed?

**Comment by Jony-Gays** [comment] 2023-02-12 18:56
To be honest I faced the exact same problem, I fully understand the problem the poster had, but it seems he didn't describe the problem clearly enough for the developer to understand what was happening. Now, I will describe the problem exactly.

This is actually a very simple problem, first of all, when I enable Lenovo Hotkeys, and I try to use Fn+F* to open or close the microphone or touchpad, there will be the following notification p1e [p1]
![P1](https://user-images.githubusercontent.com/34362472/218330000-8bd4311c-0f68-4b46-950a-6c05d2ff9592.png)
So far everything is fine.

However when I use the toolbox to close Lenovo Hotkeys, the Fn shortcut notification becomes [P2]. It's like a black board.
At the same time I found the reason for its problem.------
1. Your default setting is the bottom right corner 
2. The size of the notification box is wrong
![P2](https://user-images.githubusercontent.com/34362472/218330282-17bc896d-0a23-40ed-9dff-cb4605ae9793.png)

When I reposition the notification box to the center button, I will see "Notification bar with normal content but severe size problems" [P3]
![P3](https://user-images.githubusercontent.com/34362472/218330512-9b8c1ad4-677d-4903-a22b-3529f68a844b.png)

This is all the description of the bug

Version

2.9.1

OS
Windows 11 22H2

Device
Lenovo Legion R7000P2020H

BIOS version
LENOVO FSCN26WW, 22/9/9

What's wrong? ^1
If Disable Lenovo hotkeys,Fn+F* can not display the normal notification icon

How to reproduce the bug? 
Turn off the touchpad or microphone by Fn+F*

What is the behavior that you expected? ^2
It should show "Touchpad off" 
I will show with Pic

Logs
No logs.

**Comment by BartoszCichecki** [comment] 2023-02-12 22:01
> To be honest I faced the exact same problem, I fully understand the problem the poster had, but it seems he didn't describe the problem clearly enough for the developer to understand what was happening. Now, I will describe the problem exactly.

No, this is a different problem than the one you have.

**Comment by BartoszCichecki** [comment] 2023-02-17 11:43
Closing the issue since there doesn't seem to be any easy fix for this issue.

**Closed by BartoszCichecki** 2023-02-17 11:43 UTC
Labels: bug, help wanted, on hold
