### ISSUE TITLE
[FEAT]: Adapt to Y9000X back button light switching prompt

### ISSUE THREAD

**Issue by rospod** [BartoszCichecki/LenovoLegionToolkit#428] opened 2022-11-30 14:05 UTC
### Version

2.7.0

### OS

Windows 11 22H2 build 22624.819

### Device

Legion Y9000X IAH7 / Legion S7 16IAH7 Type 82TF

### Is your feature request related to a problem?

Using Legion Zone (China Mainland), with pressing Fn+U ,it gives me prompt like Microphone, Caps Lock , Num Lock and so on. But with Lenovo Legion Toolkit, in the apps, neither gives me control back button light in the backlight, nor show the prompt when I switch the light, Fn+U works, but I need Prompt and settings in the app.

### How would you like the problem to be solved?

Using a prompt like microphone , Caps Lock...
and 
show the setings in the keyboard light settings

### What alternatives have you considered?

Legion Zone(Mainland China)

**Comment by BartoszCichecki** [comment] 2022-11-30 14:06
Duplicate of #223

**Closed by BartoszCichecki** 2022-11-30 14:06 UTC
Labels: feature
