### ISSUE TITLE
[FEAT] Battery Charge Threshold

### ISSUE THREAD

**Issue by thecedars** [BartoszCichecki/LenovoLegionToolkit#1372] opened 2024-07-20 17:57 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Win 11 Home; Version 10.0.22631 Build 22631

### Device

Legion 5P-15ARH05H

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

https://pcsupport.lenovo.com/us/en/videos/VID500054

Second 52; Battery Charge Threshold

### What alternatives have you considered?

Lenovo Vantage

**Comment by BartoszCichecki** [comment] 2024-07-20 19:03
Duplicate of #564

**Closed** 2024-07-20 19:03 UTC
Labels: feature

**Comment by BartoszCichecki** [comment] 2024-07-20 19:04
And duplicate of #991
