### ISSUE TITLE
[FEAT]: AI Engine

### ISSUE THREAD

**Issue by matias1233218** [BartoszCichecki/LenovoLegionToolkit#237] opened 2022-09-29 05:22 UTC
### Version

2.6.0

### OS

Windows 10 21H2 build 19044.2006

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

It is more of a detail, LLT is an almost perfect tool, it fulfills everything that vantage does, without the resources that vantage consumes, in addition to not having advertising and since 2.6.0 my spectrum keyboard works with LLT, despite not specifying your support.

I would definitely disable vantage if it wasn't for one thing...
which is the "AI ENGINE" from what I was seeing is not an "AI" but are preset tdp profiles for various situations, but when comparing with "performance mode", I realize that the ai engine achieves a better performance at lower temperatures.

### How would you like the problem to be solved?

with "AI ENGINE" LLT would be universally better than vantage and therefore vantage would no longer be necessary.

### What alternatives have you considered?

the alternative I use is basically to use both, vantage and LLT

### Additional information

without AI ENGINE
![Apex_Legends_Screenshot_2022 09 17_-_22 40 52 96](https://user-images.githubusercontent.com/107080783/192945170-e73a3bde-ebd6-4818-84fa-d2324b4545cd.png)

with AI ENGINE
![Apex_Legends_Screenshot_2022 09 17_-_22 52 52 80](https://user-images.githubusercontent.com/107080783/192945177-63cbe5b3-325f-48da-8739-0649be4baa76.png)

**Comment by BartoszCichecki** [comment] 2022-09-29 07:36
As written in FAQ: https://github.com/BartoszCichecki/LenovoLegionToolkit#i-cant-find-legion-ai-engine-option, AI Engine is not supported and it is almost always better to use Performance.

I don't see this changing in the near future, but if I ever find a way to implement it without Vantage bloat I'll add it. For now though there is no plan to do it.

Related: #166

**Comment by BartoszCichecki** [comment] 2022-09-29 20:56
Good news! After giving this a thought, I decided to implement it in the end.

**Comment by BartoszCichecki** [comment] 2022-09-29 20:58
However, I will close issue as duplicate of #166 because it was already reported. What is important for you is that this will come in next release most likely.

**Closed by BartoszCichecki** 2022-09-29 20:58 UTC
Labels: duplicate, feature
