### ISSUE TITLE
Double pop-up when hovering over the LLT tray icon

### ISSUE THREAD

**Issue by MinionAttack** [BartoszCichecki/LenovoLegionToolkit#1354] opened 2024-07-01 19:10 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 11 Pro 23H2 Build 22631.3810

### Device

Legion 7 Gen 7 16ARHA7

### BIOS version

K9CN46WW

### What's wrong?

When hovering over the application icon in the system tray, the system pop-up is displayed without text next to the application pop-up.

Working:
<img width="235" alt="Pop-up" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/10078549/17f17947-1a74-4e75-aeb5-b9a6909d5dad">
Not working: 
<img width="386" alt="Pop-up (LLT)" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/10078549/585fab73-e665-4157-ba2c-176de93945b0">

### How to reproduce the bug?

1. Start the application.
2. Wait until the icon apperars in the system tray.
3. Hover the cursor over it.
4. The system pop-up is displayed without text next to the application pop-up.

### What is the behavior that you expected?

Either only the LLT application pop-up appears, or if both are displayed, the appropriate text appears in the system pop-up (the name of the application?). Although I think only the LLT application's pop-up should be displayed, as two pasted/overlapping ones wouldn't look right.

### Logs

I think this problem does not require the application logs.

### Additional information

Thank you very much for your work with this application.

**Comment by BartoszCichecki** [comment] 2024-07-01 21:21
Duplicate of #625

**Closed by BartoszCichecki** 2024-07-01 21:21 UTC
Labels: bug

**Comment by MinionAttack** [comment] 2024-07-01 21:23
Sorry for the duplication, looking through the titles I didn't realise it was the same thing.

**Comment by BartoszCichecki** [comment] 2024-07-01 21:27
No worries. That's why I tag issues like this - hopefully they will be easier to find.
