### ISSUE TITLE
App will not start

### ISSUE THREAD

**Issue by cpowell** [BartoszCichecki/LenovoLegionToolkit#1313] opened 2024-05-30 15:10 UTC
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.0, 2.21,3

### OS

Win 11 Pro 23H2 22631.3593

### Device

Legion Pro 7 16IRX8H

### BIOS version

KWCN42WW

### What's wrong?

Strangely, the app which HAD been working fine, just won't start any longer - at all. Not even with `--trace` enabled. No log or anything at all appears in `AppData\Local\LenovoLegionToolKit`.

Fully shut down and restarted the machine a couple times; no change.

Is there a way I can more clearly diagnose the startup issue?

### How to reproduce the bug?

Start LLT with --trace per the Readme instructions.

No icon appears; no program in Task Manager; no output in logs directory.

### What is the behavior that you expected?

LLT runs (which it used to)

### Logs

Not available.

**Comment by cpowell** [comment] 2024-05-30 17:07
A bit more info: downloaded the source, opened solution in Visual Studio. When attempting to debug the program, this is the output:

`The program '[31968] Lenovo Legion Toolkit.exe' has exited with code 2147516563 (0x80008093).`

**Comment by BartoszCichecki** [comment] 2024-05-30 18:43
Hmmm... this is a tough one. I have been searching for the error code `0x80008093` and nothing relevant seems to come up. The fact that no log is produced would indicate that the process crashes before the actual app starts, which is strange, but not impossible. I found a [list of .NET error codes](https://github.com/dotnet/runtime/blob/main/docs/design/features/host-error-codes.md) where this error is lister, but I am not sure if its relevant.

I would try a couple of things:
1. Run the installer for LLT again (without uninstalling it) - this will help us troubleshoot if files were corrupted
2. Re-install .NET ([link](https://download.visualstudio.microsoft.com/download/pr/0ff148e7-bbf6-48ed-bdb6-367f4c8ea14f/bd35d787171a1f0de7da6b57cc900ef5/windowsdesktop-runtime-8.0.5-win-x64.exe)) - this will help us troubleshoot if maybe .NET was corrupted

I am doubtful if that will help, but it's worth a shot. It might also be idea to make sure Windows is healthy with `sfc /scannow`.

**Comment by MinionAttack** [comment] 2024-05-30 19:16
Hi, I am writing to report the same problem after upgrading Windows 11 with the update I was getting (kb5037853).

I was going to open an issue but I see you have already opened one.

Best regards.

**Comment by MinionAttack** [comment] 2024-05-30 19:28
Ok, sorry for the double post. I have been able to fix it. What I did:

1. Download aspnetcore-runtime-8.0.6-win-x64.exe and repair.
2. Download  windowsdesktop-runtime-8.0.6-win-x64 and repair.
2.1 Only the second one is necessary (as it warned me that it could not repair because there was a program open - LLT), but as I have both installed I wanted to make sure.
3. Download the latest version of Lenovo Legion Toolkit and install ti again.
4. As soon as it is installed, when LLT starts up, the icon appears again in the system tray. I reboot the laptop and it starts up again without any problems at Windows startup.
5. 
If you need more information, please do not hesitate to ask me.

Best regards.

**Comment by BartoszCichecki** [comment] 2024-05-30 19:36
Just installed KB5037853. After the restart LLT did not appear in tray, but I could see it on process list in Task Manager. Restarted again and everything seems to be working fine. I did not have to reinstall .NET, though.

Hard to say if is caused by KB5037853, but definitely seems like something is up with it.

@cpowell let me know if reinstalling .NET fixes the problems for you. Anyway I am pinning this issue so it's easier to find.

**Comment by cpowell** [comment] 2024-05-30 19:47
Hmm. I appreciate that it's not just me, but I'm sad to report that @MinionAttack 's repair steps didn't fix it for me. I tried two ways:

1. Using the pure runtimes that they mentioned.
2. Since I have the full dotnet SDK installed anyway, doing an install/repair using `dotnet-sdk-8.0.301-win-x64.exe`

(...and then reinstalling LLT without removing it)

Sadly neither choice has fixed it for me. LLT flashes in Task Manager for a moment but then immediately exits.

Regards,
Chris

**Comment by cpowell** [comment] 2024-05-30 19:49
Oh, one additional note: I do not yet have KB5037853 installed. It's marked as 'preview' so I did not trigger it yet.

If installing KB-853 might actually get me un-stuck, I'm willing to try it. :-)

**Comment by BartoszCichecki** [comment] 2024-05-30 20:17
Damn.. So it seems like these issues aren't related. Very strange... Did you check Event Viewer? Anything interesting there?

**Comment by cpowell** [comment] 2024-05-30 20:22
I found the following under Windows Logs\Application:

```Faulting application name: Lenovo Legion Toolkit.exe, version: 2.22.1.0, time stamp: 0x66470000
Faulting module name: hostpolicy.dll, version: 8.0.624.26715, time stamp: 0x66479d24
Exception code: 0xc0000005
Fault offset: 0x000000000000be57
Faulting process id: 0x0x4EFC
Faulting application start time: 0x0x1DAB2CC3958E1B7
Faulting application path: C:\Users\chris\AppData\Local\Programs\LenovoLegionToolkit\Lenovo Legion Toolkit.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.6\hostpolicy.dll
Report Id: 6ab63ce5-b05d-4d29-82d0-3859df8ded8f
Faulting package full name: 
Faulting package-relative application ID: ```

**Comment by BartoszCichecki** [comment] 2024-05-30 20:25
I think at this point the most I can do is to create an issue for the .NET team and see if they might have a clue...

**Comment by BartoszCichecki** [comment] 2024-05-30 20:26
Actually, @cpowell can you check if that file is even there `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.6\hostpolicy.dll`?

**Comment by cpowell** [comment] 2024-05-30 20:32
I confirmed that the file does exist there, yes.

**Comment by BartoszCichecki** [comment] 2024-05-30 20:34
OK, this might be a long shot, but let's try reinstalling this specific version of .NET runtime: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.6-windows-x64-installer

If that won't help, we might need to report this to dotnet bois.

**Comment by cpowell** [comment] 2024-05-30 20:41
No difference, I'm afraid. But I'm grateful for the help. Let me know what the .NET team offers and I'll be happy to test further.

**Comment by cpowell** [comment] 2024-05-30 22:43
I have restored LLT functionality here as follows:

1. Removed .NET SDK 8.0.6 by running Visual Studio Installer and un-checking the category ".NET desktop development".
2. Ensured no other 8.0.6 runtimes were on machine, rebooted.
3. Downloaded 8.0.5 runtimes from https://dotnet.microsoft.com/ and installed them.

App now runs correctly. It seems something in the 8.0.6 update is to blame.

**Comment by BartoszCichecki** [comment] 2024-05-30 22:47
Great news! In that case, I am closing this issue and pinning it for now.

**Closed by BartoszCichecki** 2024-05-30 22:47 UTC
Labels: bug, blocked

**Comment by cpowell** [comment] 2024-05-31 19:40
Adding a little more just to preserve the knowledge...

Today I found that Windows had auto-updated my runtimes to 8.0.6 for me; LLT again would not start.

I went into Add Remove Programs, selected each, and performed a Modify->Repair. (There were two.) To my pleasant surprise this worked; LLT is running again with .NET 8.0.6 runtimes.
